"""empty message

Revision ID: 343724aceda6
Revises: 91cbebea82b3
Create Date: 2020-03-16 19:55:20.076364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343724aceda6'
down_revision = '91cbebea82b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('currently_seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('currently_seeking_talent_description', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'genres')
    op.drop_column('Venue', 'currently_seeking_talent_description')
    op.drop_column('Venue', 'currently_seeking_talent')
    # ### end Alembic commands ###
